### ISSUE TITLE
Cryptographic hashes

### ISSUE THREAD

**Issue by Kocharyan97** [QT-Lab/tech-meetups#5]
**We can talk about cryptographic hashes.**

What is hashing?

Hashing is a method of cryptography that converts any form of data into a unique string of text. Any piece of data can be hashed, no matter its size or type. In traditional hashing, regardless of the data’s size, type, or length, the hash that any data produces is always the same length. A hash is designed to act as a one-way function — you can put data into a hashing algorithm and get a unique string, but if you come upon a new hash, you cannot decipher the input data it represents. A unique piece of data will always produce the same hash.

**Comment by amuradyan** [comment]
We sure can. I was thinking we can even implement one.  Have you seen the [VSH](https://en.wikipedia.org/wiki/Very_smooth_hash) /the [paper](https://eprint.iacr.org/2005/193.pdf)/?

Are there, maybe, any specific things you want to know about cryptographic hashes?

**Comment by Kocharyan97** [comment]
I've only read about it.But for clear understanding i would like to implement one.

**Comment by amuradyan** [comment]
@Kocharyan97 I've been looking at some algorithms and their implementations, and though the documentation is there, it is very technical and the implementation is as well. I don't see how doing this will create more value rather than just wasting our time, so I'd propose you try and implement one and we can look at it together. I suggest you check out the [MD5](https://en.wikipedia.org/wiki/MD5) /the pseudocode is very helpful/.
